services:
  nodeapp:
    build: .
    container_name: web-qr-node-app
    restart: always
    ports:
      - "4000:4000"
    networks:
      - appnet
    volumes:
      - .env:/app/.env
      - ./public/styles.css:/app/public/styles.css

  nginx:
    image: nginx:latest
    container_name: web-qr-nginx
    restart: always
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nodeapp
    networks:
      - appnet


networks:
  appnet:
