version: '3.8'

services:
  nodeapp:
    build: .
    container_name: my-node-app
    restart: always
    ports:
      - "3000:3000"
    networks:
      - appnet

  nginx:
    image: nginx:latest
    container_name: my-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nodeapp
    networks:
      - appnet


networks:
  appnet:
